### ISSUE TITLE
Unable to generate in Mathematica 12

### ISSUE THREAD

**Issue by bibekpokharel** [szhorvat/MaTeX#29] opened 2019-10-22 16:13 UTC
First of all, thank for this amazing package. I am running Mathematica 12 on macOS Catalina and getting errors. I have attached screenshot below. Let me know if the issue is not with MaTeX but with TeX or Catalina instead. 
![image](https://user-images.githubusercontent.com/16129329/67306666-3313d200-f4ac-11e9-92e3-42944969bc87.png)

**Comment by szhorvat** [comment] 2019-10-22 17:41
Please evaluate the troubleshooting notebook linked at the very end of http://szhorvat.net/mathematica/MaTeX and email it to me. It might give better hints.

Please also check that `RunProcess` works (use the documentation examples).

It is concerning to see ``MaTeX`Private`RunProcess``. It would indicate that `RunProcess` was not recognized as a System symbol. Can you give *detailed* steps to reproduce the issue, starting with a fresh Mathematica (restart both kernel and front end please)?

**Comment by szhorvat** [comment] 2019-10-23 08:57
I have not yet received an email from you.

**Comment by bibekpokharel** [comment] 2019-10-23 18:53
Sent you the troubleshooting notebook. Not quite certain what you mean by

> Please also check that RunProcess works (use the documentation examples).

**Comment by szhorvat** [comment] 2019-10-23 19:02
Please look up the `RunProcess` function in the documentation. The documentation page has many examples. Try a few of them and confirm that the function works as described in the documentation. 

From the troubleshooting notebook you sent, it appears that it simply does not work. Do you have anything in your `Kernel/init.m` file?

**Comment by szhorvat** [comment] 2019-10-23 19:05
Could you also try to evaluate the following?

    Names["RunProcess"]

What is the output?

**Comment by szhorvat** [comment] 2019-10-24 07:59
After trying the above, can you try to evaluate

```mma
PacletManager`RebuildPacletData[]
```

then restart Mathematica? Does it fix `RunProcess` not working?

**Comment by bibekpokharel** [comment] 2019-10-24 20:21
This fixed the problem. I am still unsure what happened to cause the problem to begin with.

Also, I am also having trouble importing CSV files in Mathematica so there might be a bigger issue at play here.

Sincerely,
Bibek Pokharel

**Comment by szhorvat** [comment] 2019-10-25 12:23
It seems the problem is with Mathematica then. I am closing this issue. If you see similar problems (i.e. some built-in functions such as `RunProcess` do not work, independently of MaTeX), I suggest contacting Wolfram.

**Closed as completed by szhorvat** 2019-10-25 12:23 UTC
